# Generated by Django 5.1.4 on 2025-01-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('last_transaction_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('promil', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.IntegerField()),
                ('best_turnover', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_turnover', models.DecimalField(decimal_places=2, max_digits=15)),
                ('company_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Stock Data',
                'verbose_name_plural': 'Stock Data',
            },
        ),
    ]
